-- 5월 식품들의 총매출 조회하기
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT
  JOIN FOOD_ORDER USING(PRODUCT_ID)
WHERE PRODUCE_DATE LIKE "2022-05-%"
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC