-- 그룹별 조건에 맞는 식당 목록 출력하기
SELECT MEMBER_NAME, REVIEW_TEXT,
  DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS "REVIEW_DATE"
FROM REST_REVIEW R
INNER JOIN MEMBER_PROFILE P
  ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID = (SELECT MEMBER_ID
                     FROM REST_REVIEW
                     GROUP BY MEMBER_ID
                     ORDER BY COUNT(REVIEW_SCORE) DESC
                     LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT


WITH A as (SELECT MEMBER_ID,COUNT(MEMBER_ID)as MCV
                FROM REST_REVIEW
                GROUP BY 1
                order by 2 desc
                limit 1)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d")REVIEW_DATE
FROM MEMBER_PROFILE as m, REST_REVIEW as r , A
WHERE m.MEMBER_ID = r.MEMBER_ID
AND m.MEMBER_ID= A.MEMBER_ID
ORDER BY 3,2