-- 상품을 구매한 회원 비율 구하기
-- 1
SELECT YEAR(SALES_DATE) AS "YEAR",
  MONTH(SALES_DATE) AS "MONTH",
  COUNT(DISTINCT USER_ID) AS "PUCHASED_USERS",
  ROUND(COUNT(DISTINCT USER_ID) / 
    (SELECT COUNT(*) 
      FROM USER_INFO
      WHERE YEAR(JOINED) = 2021), 1) AS "PUCHASED_RATIO"
FROM ONLINE_SALE
WHERE USER_ID IN 
  (SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;

-- 2
WITH USER_T AS (SELECT USER_ID
                FROM USER_INFO
                WHERE YEAR(JOINED)=2021)
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT(USER_ID)) PUCHASED_USERS,
ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(USER_ID) FROM USER_T),1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
WHERE O.USER_ID IN (SELECT * FROM USER_T)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1, 2;