-- 서울에 위치한 식당 목록 출력하기
SELECT B.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW A
  LEFT JOIN REST_INFO B
  ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY B.REST_ID
ORDER BY SCORE DESC, B.FAVORITES DESC