-- 연도별 대장균 크기의 편차 구하기
-- 윈도우 함수 사용
-- YEAR()는 MySQL 외의 다른 DBMS에서는 동작하지 않을 수 있으니 이런 경우엔 EXTRACT()를 사용
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
  MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,
  ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV


-- left join
select year(a.DIFFERENTIATION_DATE) as YEAR, (b.SIZE-a.SIZE_OF_COLONY) as YEAR_DEV, a.ID
from ECOLI_DATA as a
left join (select year(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) as SIZE
        from ECOLI_DATA
        group by year(DIFFERENTIATION_DATE)) as  b
on year(a.DIFFERENTIATION_DATE)=b.YEAR
order by YEAR, YEAR_DEV


-- 서브쿼리사용
WITH MAX_SIZE AS
(SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
FROM ECOLI_DATA
GROUP BY 1)

SELECT M.YEAR, (MAX_SIZE - E.SIZE_OF_COLONY) YEAR_DEV, ID
FROM ECOLI_DATA E
LEFT JOIN MAX_SIZE M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY 1, 2