-- 입양 시각 구하기(2)
SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM 
  (SELECT (ROW_NUMBER() OVER () - 1) AS HOUR
    FROM ANIMAL_OUTS
    LIMIT 24) AS 24HOURS_TABLE 
LEFT JOIN ANIMAL_OUTS ON HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR
;


WITH RECURSIVE HOURS AS (
    SELECT 0 AS NUM 
    UNION ALL
    SELECT NUM+1 FROM HOURS
    WHERE NUM < 23
)
SELECT HOURS.NUM AS HOUR, COUNT(AO.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS AO
RIGHT JOIN HOURS ON EXTRACT(HOUR FROM AO.DATETIME) = HOURS.NUM
GROUP BY HOURS.NUM
ORDER BY HOUR
;