-- 잡은 물고기의 평균 길이 구하기
SELECT ROUND(AVG(IFNULL(LENGTH, 10)), 2) AS AVERAGE_LENGTH
FROM FISH_INFO


SELECT ROUND(AVG(CASE 
                 WHEN LENGTH <= 10 OR LENGTH IS NULL THEN 10
                 ELSE LENGTH END), 2) AS AVERAGE_LENGTH
FROM FISH_INFO