-- 조건에 맞는 사용자 정보 조회하기
SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY, " ", B.STREET_ADDRESS1, " ", B.STREET_ADDRESS2) AS 전체주소, CONCAT(substr(B.TLNO,1,3), '-', substr(B.TLNO,4,4), '-', substr(B.TLNO,8,4)) AS 전화번호
FROM USED_GOODS_BOARD A
  JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
GROUP BY 1 HAVING COUNT(WRITER_ID) >= 3
ORDER BY 1 DESC