-- 조건에 맞는 사용자와 총 거래금액 조회하기
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
  JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE STATUS = "DONE"
GROUP BY WRITER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES