-- 취소되지 않은 진료 예약 조회하기
SELECT AP.APNT_NO, PT.PT_NAME, PT.PT_NO, AP.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
  JOIN PATIENT PT ON AP.PT_NO = PT.PT_NO
  JOIN DOCTOR DR ON AP.MDDR_ID = DR.DR_ID
WHERE AP.APNT_YMD LIKE "2022-04-13%" AND AP.APNT_CNCL_YN = "N"
ORDER BY AP.APNT_YMD